//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18034
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicasaAdmin.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Add", ReplyAction="http://tempuri.org/IUserService/AddResponse")]
        bool Add(string first_name, string last_name, string login, string mail, string pwd, bool level);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Delete", ReplyAction="http://tempuri.org/IUserService/DeleteResponse")]
        bool Delete(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Check_password", ReplyAction="http://tempuri.org/IUserService/Check_passwordResponse")]
        bool Check_password(string login, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Get_User_ID", ReplyAction="http://tempuri.org/IUserService/Get_User_IDResponse")]
        int Get_User_ID(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Get_User_Level", ReplyAction="http://tempuri.org/IUserService/Get_User_LevelResponse")]
        bool Get_User_Level(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Get_User", ReplyAction="http://tempuri.org/IUserService/Get_UserResponse")]
        DB.User Get_User(string login);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : PicasaAdmin.ServiceReference1.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<PicasaAdmin.ServiceReference1.IUserService>, PicasaAdmin.ServiceReference1.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Add(string first_name, string last_name, string login, string mail, string pwd, bool level) {
            return base.Channel.Add(first_name, last_name, login, mail, pwd, level);
        }
        
        public bool Delete(string login) {
            return base.Channel.Delete(login);
        }
        
        public bool Check_password(string login, string pwd) {
            return base.Channel.Check_password(login, pwd);
        }
        
        public int Get_User_ID(string login) {
            return base.Channel.Get_User_ID(login);
        }
        
        public bool Get_User_Level(string login) {
            return base.Channel.Get_User_Level(login);
        }
        
        public DB.User Get_User(string login) {
            return base.Channel.Get_User(login);
        }
    }
}
