//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18034
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicasaWPF.Image_Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImageInfo", Namespace="http://schemas.datacontract.org/2004/07/PicasaServices")]
    [System.SerializableAttribute()]
    public partial class ImageInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        private int AlbumField;
        
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Album {
            get {
                return this.AlbumField;
            }
            set {
                if ((this.AlbumField.Equals(value) != true)) {
                    this.AlbumField = value;
                    this.RaisePropertyChanged("Album");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImageDownloadResponse", Namespace="http://schemas.datacontract.org/2004/07/PicasaServices")]
    [System.SerializableAttribute()]
    public partial class ImageDownloadResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.IO.Stream ImageDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.IO.Stream ImageData {
            get {
                return this.ImageDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageDataField, value) != true)) {
                    this.ImageDataField = value;
                    this.RaisePropertyChanged("ImageData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Image_Service.IImageService")]
    public interface IImageService {
        
        // CODEGEN : La génération du contrat de message depuis l'opération Add n'est ni RPC, ni encapsulée dans un document.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/Add", ReplyAction="http://tempuri.org/IImageService/AddResponse")]
        PicasaWPF.Image_Service.AddResponse Add(PicasaWPF.Image_Service.ImageUploadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/Delete", ReplyAction="http://tempuri.org/IImageService/DeleteResponse")]
        bool Delete(int id, int idAlbum);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (ImageDownloadRequest) du message ImageDownloadRequest ne correspond pas à la valeur par défaut (Get_Image)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/Get_Image", ReplyAction="http://tempuri.org/IImageService/Get_ImageResponse")]
        PicasaWPF.Image_Service.ImageDownloadResponse1 Get_Image(PicasaWPF.Image_Service.ImageDownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/Get_Image_Name", ReplyAction="http://tempuri.org/IImageService/Get_Image_NameResponse")]
        string Get_Image_Name(int id, int idAlbum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/Get_Image_ID", ReplyAction="http://tempuri.org/IImageService/Get_Image_IDResponse")]
        int Get_Image_ID(int idAlbum, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/Get_Images_From_Album", ReplyAction="http://tempuri.org/IImageService/Get_Images_From_AlbumResponse")]
        PicasaWPF.Image_Service.ImageDownloadResponse[] Get_Images_From_Album(int idAlbum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/Get_Images_ID_From_Album", ReplyAction="http://tempuri.org/IImageService/Get_Images_ID_From_AlbumResponse")]
        int[] Get_Images_ID_From_Album(int idAlbum);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImageUploadRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ImageUploadRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public PicasaWPF.Image_Service.ImageInfo ImageInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream ImageData;
        
        public ImageUploadRequest() {
        }
        
        public ImageUploadRequest(PicasaWPF.Image_Service.ImageInfo ImageInfo, System.IO.Stream ImageData) {
            this.ImageInfo = ImageInfo;
            this.ImageData = ImageData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        public AddResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImageDownloadRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ImageDownloadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public PicasaWPF.Image_Service.ImageInfo ImageInfo;
        
        public ImageDownloadRequest() {
        }
        
        public ImageDownloadRequest(PicasaWPF.Image_Service.ImageInfo ImageInfo) {
            this.ImageInfo = ImageInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImageDownloadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ImageDownloadResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream ImageData;
        
        public ImageDownloadResponse1() {
        }
        
        public ImageDownloadResponse1(System.IO.Stream ImageData) {
            this.ImageData = ImageData;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IImageServiceChannel : PicasaWPF.Image_Service.IImageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImageServiceClient : System.ServiceModel.ClientBase<PicasaWPF.Image_Service.IImageService>, PicasaWPF.Image_Service.IImageService {
        
        public ImageServiceClient() {
        }
        
        public ImageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PicasaWPF.Image_Service.AddResponse PicasaWPF.Image_Service.IImageService.Add(PicasaWPF.Image_Service.ImageUploadRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(PicasaWPF.Image_Service.ImageInfo ImageInfo, System.IO.Stream ImageData) {
            PicasaWPF.Image_Service.ImageUploadRequest inValue = new PicasaWPF.Image_Service.ImageUploadRequest();
            inValue.ImageInfo = ImageInfo;
            inValue.ImageData = ImageData;
            PicasaWPF.Image_Service.AddResponse retVal = ((PicasaWPF.Image_Service.IImageService)(this)).Add(inValue);
        }
        
        public bool Delete(int id, int idAlbum) {
            return base.Channel.Delete(id, idAlbum);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PicasaWPF.Image_Service.ImageDownloadResponse1 PicasaWPF.Image_Service.IImageService.Get_Image(PicasaWPF.Image_Service.ImageDownloadRequest request) {
            return base.Channel.Get_Image(request);
        }
        
        public System.IO.Stream Get_Image(PicasaWPF.Image_Service.ImageInfo ImageInfo) {
            PicasaWPF.Image_Service.ImageDownloadRequest inValue = new PicasaWPF.Image_Service.ImageDownloadRequest();
            inValue.ImageInfo = ImageInfo;
            PicasaWPF.Image_Service.ImageDownloadResponse1 retVal = ((PicasaWPF.Image_Service.IImageService)(this)).Get_Image(inValue);
            return retVal.ImageData;
        }
        
        public string Get_Image_Name(int id, int idAlbum) {
            return base.Channel.Get_Image_Name(id, idAlbum);
        }
        
        public int Get_Image_ID(int idAlbum, string name) {
            return base.Channel.Get_Image_ID(idAlbum, name);
        }
        
        public PicasaWPF.Image_Service.ImageDownloadResponse[] Get_Images_From_Album(int idAlbum) {
            return base.Channel.Get_Images_From_Album(idAlbum);
        }
        
        public int[] Get_Images_ID_From_Album(int idAlbum) {
            return base.Channel.Get_Images_ID_From_Album(idAlbum);
        }
    }
}
